language: python
python:
  - "3.5"

services:
  - postgresql

before_script:
  - psql -c "create database travisdb;" -U postgres

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - export DB_ENGINE='django.db.backends.postgresql_psycopg2'
  - export DB_NAME='travisdb'
  - export DB_HOST='localhost'
  - export SECRET_KEY='potatotest'
  - cd collateral_consequence
  - python manage.py migrate
  - coverage run manage.py test
  - cp .coverage ../

after_script: coveralls